version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=recordings
    restart: always
    ports:
      - 3306:3306
